### ISSUE TITLE
won count from TradeAnalyzer returns bool, not int

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#36]
:
thestrats = cerebro.run()
thestrat = thestrats[0]
res = thestrat.myanalyzer.trade_analyzer.get_analysis()

The won count res['won']['total'] returns `<type 'numpy.bool_'>`, but the lost count res['lost']['total'] returns `<type 'int'>`

**Comment by mementum** [comment]
Hi. I fail to understand how the code may have produced a `<type 'numpy.bool_>`, given the platform is numpy independent (plotting uses matplotlib, but the plotting code pulls in the existing data, it does not write data to any object)

Moreover, I just run the analyzer-annualreturn.py sample adding a "TradeAnalyzer" and this is the printout for won toal and lost total

```
            """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
            - won:
              - total: 17
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              - pnl:
                - total: 13749.3
                - average: 808.7824
                - max: 3081.2
            """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
            - lost:
              - total: 39
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              - pnl:
                - total: -12553.7
                - average: -321.8897
                - max: -941.3
```

There is no "bool" in won total. A plain int with a value of 17.

May you have some code which shows the problem?
